# Generated by Django 4.0.5 on 2022-06-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_details_kcno'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('pub_year', models.CharField(max_length=25)),
                ('publisher', models.CharField(max_length=500)),
                ('urls', models.CharField(max_length=250)),
                ('urlm', models.CharField(max_length=250)),
                ('urll', models.CharField(max_length=250)),
                ('file_path', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='user_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('query', models.CharField(max_length=100)),
                ('dt', models.CharField(max_length=25)),
                ('tm', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='age',
        ),
        migrations.AddField(
            model_name='user_details',
            name='dob',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='status',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_details',
            name='contact',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='lname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='pin',
            field=models.CharField(max_length=25),
        ),
    ]
